### ISSUE TITLE
Partially missing data for some of the earlier years and no data for 2015,2016

### ISSUE THREAD

**Issue by chaltik** [David-Woroniuk/FedTools#4]
Amazing package, thanks for putting in the work. 
Not sure if it is a recent issue, but it seems most of the meetings are missing for 1995-1998 and all of them for 2015, 2016.
![image](https://user-images.githubusercontent.com/16768683/205841537-12aa425a-6c87-4118-875b-1f71de22e35f.png)
However, the corresponding pages at the fed (https://www.federalreserve.gov/monetarypolicy/fomchistoricalYYYY.htm) seem to all contain 8 meetings for those years

**Comment by David-Woroniuk** [comment]
I will take a look into this and come back - my initial guess would be an issue with the gateway proxy which is being used.

**Comment by RogerRendon** [comment]
Same problem here! 
![fedtools_md](https://user-images.githubusercontent.com/22053596/207432873-ae0b8461-d5e9-4891-8cda-fb904c8bd761.PNG)

**Comment by David-Woroniuk** [comment]
Hi gents - apologies for my slow response on this.  The 'bug' that you have spotted relates to the default arguments passed as arguments.

In order to collect the full information (including 2014 -> 2017), please use the below code:

```python
    monetary_policy = MonetaryPolicyCommittee(
        main_url='https://www.federalreserve.gov',
        calendar_url='https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
        start_year=1994,
        historical_split=2016,
        verbose=True,
        thread_num=10)
    dataset = monetary_policy.find_statements()
```

Note that the ```historical_split``` argument has been updated from the default argument ```2014``` to ```2016```, and we are calling the method ```find_statements()``` on the class instance. 

Marking as complete, but I shall update the default args.

**Comment by RogerRendon** [comment]
Thank you, David! I'll be testing this in the few next days.

**Comment by chaltik** [comment]
Thanks! I will give it a spin as  well.
I might have found an alternative way to get these from FRASER as well -
will share.
